version: '3.3'

services:
  drupal:
    image: bitnami/drupal:latest
    ports:
      - '80:8080'
    environment:
      - DRUPAL_DATABASE_HOST=db
      - DRUPAL_DATABASE_PORT_NUMBER=3306
      - DRUPAL_DATABASE_NAME=drupal
      - DRUPAL_DATABASE_USER=YAM428
      - DRUPAL_DATABASE_PASSWORD=30718034
    volumes:
      - drupal_data:/bitnami/drupal
    depends_on:
      - db
    networks:
      - drupal_network

  db:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_USER=drupal
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=drupal
    volumes:
      - db_data:/bitnami/mariadb
    networks:
      - drupal_network

  webserver:
    image: nginx
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - drupal_data:/bitnami/drupal
      - ./nginx.conf:/etc/nginx/nginx.conf
      - certbot_certs:/etc/letsencrypt
      - certbot_lib:/var/lib/letsencrypt
    depends_on:
      - drupal
    networks:
      - drupal_network

  certbot:
    image: certbot
    command: certonly --webroot --webroot-path=/var/www/html --email furkanlebitt7@gmail.com --agree-tos --no-eff-email --staging -d furkanlebit7.me
    volumes:
      - certbot_lib:/var/lib/letsencrypt
      - certbot_certs:/etc/letsencrypt
      - ./certbot_data:/var/www/html
    depends_on:
      - webserver
    networks:
      - drupal_network

volumes:
  drupal_data:
  db_data:
  certbot_certs:
  certbot_lib:

networks:
  drupal_network:

